"""
Template-generated answers for location-specific example questions.

Suggested questions that require a location ("How has the temperature changed
in {location}?") are generated by us, so no LLM is needed to interpret them —
and their answers always follow the same shape. This module computes the
numbers directly from the tile store and fills a per-question template,
producing the same (answer, locations, charts, follow_up_ids) payload as a
canned answer. The LLM remains the fallback for anything this module cannot
answer (unknown question id, missing data at the location).

Temperature values are encoded as [[C|F]] tokens, resolved by
canned._apply_unit at stream time, exactly like canned answers.
"""

from __future__ import annotations

import calendar
from typing import Any

import numpy as np

from .question_tree import QUESTION_TREE

_GLOBAL_START_YEAR = 1979


# ---------------------------------------------------------------------------
# Formatting helpers
# ---------------------------------------------------------------------------


def _tok(celsius: float, *, delta: bool = False, nd: int = 1) -> str:
    """Format a temperature as a [[C|F]] token. Delta values use scale-only conversion."""
    c = round(celsius, nd)
    f = round(c * 9 / 5 if delta else c * 9 / 5 + 32, nd)
    return f"[[{c}°C|{f}°F]]"


def _month_name(month: int) -> str:
    return calendar.month_name[month]


def _axis_month_name(axis_value: str) -> str:
    """'2003-08' → 'August 2003'."""
    year, month = str(axis_value).split("-")
    return f"{_month_name(int(month))} {year}"


# ---------------------------------------------------------------------------
# Data helpers
# ---------------------------------------------------------------------------


def _series(
    tile_store: Any, metric: str, lat: float, lon: float
) -> tuple[list, np.ndarray] | None:
    """Return (axis, values) for the snapped cell, or None if unavailable."""
    try:
        vec = tile_store.try_get_metric_vector(metric, lat, lon)
    except FileNotFoundError:
        return None
    if vec is None:
        return None
    axis = tile_store.axis(metric)
    values = np.asarray(vec, dtype=np.float64).reshape(-1)
    if axis is None or len(axis) != values.size:
        return None
    if np.count_nonzero(np.isfinite(values)) < 2:
        return None
    return list(axis), values


def _trend_per_decade(years: np.ndarray, values: np.ndarray) -> float | None:
    finite = np.isfinite(values)
    if np.count_nonzero(finite) < 2:
        return None
    return float(np.polyfit(years[finite], values[finite], 1)[0]) * 10


def _yearly(axis: list, values: np.ndarray) -> tuple[np.ndarray, np.ndarray]:
    years = np.asarray([int(str(a)[:4]) for a in axis], dtype=np.float64)
    return years, values


def _window_mean(values: np.ndarray, sl: slice) -> float | None:
    window = values[sl]
    finite = window[np.isfinite(window)]
    return float(np.mean(finite)) if finite.size else None


def _global_trend_per_decade(tile_store: Any, metric: str) -> float | None:
    agg = tile_store.aggregates.get((metric, "mean"))
    if not agg:
        return None
    globe = agg.get("regions", {}).get("globe")
    if not globe:
        return None
    values = np.asarray(
        [v if v is not None else np.nan for v in globe["values"]], dtype=np.float64
    )
    years = np.asarray(
        [int(str(a)[:4]) for a in agg["time_axis"]], dtype=np.float64
    )
    return _trend_per_decade(years, values)


def _monthly_typical_extreme(
    axis: list, values: np.ndarray, *, extreme: str, recent_years: int = 10
) -> tuple[float, int] | None:
    """
    Typical peak (or low) month over the last `recent_years` years of a
    monthly series: mean per calendar month, then max (or min) across months.
    Returns (value, month_number).
    """
    months = np.asarray([int(str(a).split("-")[1]) for a in axis])
    years = np.asarray([int(str(a)[:4]) for a in axis])
    cutoff = years.max() - recent_years + 1
    recent = years >= cutoff
    by_month: dict[int, float] = {}
    for m in range(1, 13):
        sel = values[recent & (months == m)]
        sel = sel[np.isfinite(sel)]
        if sel.size:
            by_month[m] = float(np.mean(sel))
    if not by_month:
        return None
    pick = max if extreme == "max" else min
    month = pick(by_month, key=by_month.get)
    return by_month[month], month


def _seasonal_yearly_means(
    axis: list, values: np.ndarray, months: list[int]
) -> tuple[np.ndarray, np.ndarray]:
    """Per-year mean over the given calendar months of a monthly series."""
    month_arr = np.asarray([int(str(a).split("-")[1]) for a in axis])
    year_arr = np.asarray([int(str(a)[:4]) for a in axis])
    sel = np.isin(month_arr, months)
    out_years, out_vals = [], []
    for y in np.unique(year_arr[sel]):
        vals = values[sel & (year_arr == y)]
        vals = vals[np.isfinite(vals)]
        if vals.size:
            out_years.append(float(y))
            out_vals.append(float(np.mean(vals)))
    return np.asarray(out_years), np.asarray(out_vals)


def _compare_to_global(local: float, global_: float | None) -> str:
    if global_ is None or global_ == 0:
        return ""
    ratio = local / global_
    if ratio >= 1.15:
        return f" — about {ratio:.1f}× the global average of {_tok(global_, delta=True, nd=2)} per decade"
    if ratio <= 0.85:
        return f" — slower than the global average of {_tok(global_, delta=True, nd=2)} per decade"
    return f" — close to the global average of {_tok(global_, delta=True, nd=2)} per decade"


# ---------------------------------------------------------------------------
# Per-question generators
# ---------------------------------------------------------------------------
# Each returns (answer_text, chart_spec) or None when the location has no
# usable data for the question. `label` is the display name from the map pin.


def _gen_local_temp_trend(tile_store, lat, lon, label):
    s = _series(tile_store, "t2m_yearly_mean_c", lat, lon)
    if s is None:
        return None
    axis, values = s
    years, values = _yearly(axis, values)
    trend = _trend_per_decade(years, values)
    first = _window_mean(values, slice(0, 5))
    last = _window_mean(values, slice(-5, None))
    if trend is None or first is None or last is None:
        return None
    global_trend = _global_trend_per_decade(tile_store, "t2m_yearly_mean_c")
    answer = (
        f"**{label}** has warmed at **{_tok(trend, delta=True, nd=2)} per decade** "
        f"since {int(years[0])}{_compare_to_global(trend, global_trend)}. "
        f"Its mean annual temperature rose from {_tok(first)} (average of the first five years) "
        f"to {_tok(last)} over the most recent five years."
    )
    return answer, {"metric_id": "t2m_yearly_mean_c", "show_trend": True}


def _gen_local_summer_heat(tile_store, lat, lon, label):
    s = _series(tile_store, "t2m_monthly_max_c", lat, lon)
    if s is None:
        return None
    axis, values = s
    typical = _monthly_typical_extreme(axis, values, extreme="max")
    if typical is None:
        return None
    typical_value, typical_month = typical
    idx = int(np.nanargmax(values))
    answer = (
        f"The hottest days in **{label}** typically reach about **{_tok(typical_value)}** "
        f"in {_month_name(typical_month)} (average over the last decade). "
        f"The highest temperature in our data is **{_tok(values[idx])}**, "
        f"recorded in {_axis_month_name(axis[idx])}. "
        f"The chart shows how the year's hottest days have trended over time."
    )
    return answer, {
        "metric_id": "t2m_monthly_max_c",
        "aggregate_by_year": True,
        "show_trend": True,
    }


def _gen_local_night_cold(tile_store, lat, lon, label):
    s = _series(tile_store, "t2m_monthly_min_c", lat, lon)
    if s is None:
        return None
    axis, values = s
    typical = _monthly_typical_extreme(axis, values, extreme="min")
    if typical is None:
        return None
    typical_value, typical_month = typical
    idx = int(np.nanargmin(values))
    answer = (
        f"The coldest nights in **{label}** typically drop to about **{_tok(typical_value)}** "
        f"in {_month_name(typical_month)} (average over the last decade). "
        f"The lowest temperature in our data is **{_tok(values[idx])}**, "
        f"recorded in {_axis_month_name(axis[idx])}. "
        f"The chart shows how the year's coldest nights have trended over time."
    )
    return answer, {
        "metric_id": "t2m_monthly_min_c",
        "aggregate_by_year": True,
        "show_trend": True,
    }


def _gen_rainfall_local(tile_store, lat, lon, label):
    s = _series(tile_store, "tp_annual_total_mm", lat, lon)
    if s is None:
        return None
    axis, values = s
    mean_annual = float(np.nanmean(values))
    first = _window_mean(values, slice(0, 10))
    last = _window_mean(values, slice(-10, None))
    if first is None or last is None:
        return None
    change_pct = (last - first) / first * 100 if first else 0.0
    if change_pct >= 5:
        change_txt = f"have increased by about {change_pct:.0f}%"
    elif change_pct <= -5:
        change_txt = f"have decreased by about {abs(change_pct):.0f}%"
    else:
        change_txt = "have remained roughly stable"
    answer = (
        f"**{label}** receives about **{mean_annual:,.0f} mm** of precipitation per year. "
        f"Annual totals {change_txt}, averaging {first:,.0f} mm in the first decade of the "
        f"record versus {last:,.0f} mm in the most recent decade — though year-to-year "
        f"variation is typically much larger than the long-term change."
    )
    return answer, {"metric_id": "tp_annual_total_mm"}


def _gen_local_winters(tile_store, lat, lon, label):
    s = _series(tile_store, "t2m_monthly_mean_c", lat, lon)
    if s is None:
        return None
    axis, values = s
    months = [12, 1, 2] if lat >= 0 else [6, 7, 8]
    season = "December–February" if lat >= 0 else "June–August"
    years, winter_means = _seasonal_yearly_means(axis, values, months)
    if years.size < 2:
        return None
    trend = _trend_per_decade(years, winter_means)
    first = _window_mean(winter_means, slice(0, 10))
    last = _window_mean(winter_means, slice(-10, None))
    if trend is None or first is None or last is None:
        return None
    if abs(trend) < 0.05:
        trend_txt = "stayed roughly stable"
    else:
        direction = "warmed" if trend > 0 else "cooled"
        trend_txt = (
            f"{direction} at **{_tok(abs(trend), delta=True, nd=2)} per decade**"
        )
    answer = (
        f"Winters ({season}) in **{label}** have {trend_txt} since {int(years[0])}. "
        f"A typical winter now averages {_tok(last)}, compared with {_tok(first)} "
        f"in the first decade of the record."
    )
    return answer, {
        "metric_id": "t2m_monthly_mean_c",
        "month_filter": months,
        "aggregate_by_year": True,
        "show_trend": True,
    }


def _gen_local_vs_global(tile_store, lat, lon, label):
    s = _series(tile_store, "t2m_yearly_mean_c", lat, lon)
    if s is None:
        return None
    axis, values = s
    years, values = _yearly(axis, values)
    trend = _trend_per_decade(years, values)
    global_trend = _global_trend_per_decade(tile_store, "t2m_yearly_mean_c")
    if trend is None or global_trend is None:
        return None
    ratio = trend / global_trend if global_trend else None
    if ratio is not None and ratio >= 1.15:
        verdict = f"**about {ratio:.1f}× faster than** the global average"
    elif ratio is not None and ratio <= 0.85:
        verdict = "**slower than** the global average"
    else:
        verdict = "**in step with** the global average"
    answer = (
        f"**{label}** is warming at {_tok(trend, delta=True, nd=2)} per decade — "
        f"{verdict} of {_tok(global_trend, delta=True, nd=2)} per decade. "
        f"Land locations generally warm faster than the global mean, which is pulled "
        f"down by the slower-warming oceans."
    )
    # Local series + global mean on one chart (same metric → merged by the builder).
    return answer, {
        "metric_id": "t2m_yearly_mean_c",
        "extra_region_ids": ["globe"],
    }


def _gen_sea_temp_local(tile_store, lat, lon, label):
    s = _series(tile_store, "sst_yearly_mean_c", lat, lon)
    if s is None:
        return None
    axis, values = s
    years, values = _yearly(axis, values)
    trend = _trend_per_decade(years, values)
    first = _window_mean(values, slice(0, 5))
    last = _window_mean(values, slice(-5, None))
    if trend is None or first is None or last is None:
        return None
    direction = "warmed" if trend >= 0 else "cooled"
    answer = (
        f"The sea surface near **{label}** has {direction} at "
        f"**{_tok(abs(trend), delta=True, nd=2)} per decade** since {int(years[0])}, "
        f"rising from about {_tok(first)} to {_tok(last)} "
        f"(first vs latest five-year average). Warmer coastal water affects marine life, "
        f"local weather, and — in the tropics — coral bleaching risk."
    )
    return answer, {"metric_id": "sst_yearly_mean_c", "show_trend": True}


def _gen_coral_risk_local(tile_store, lat, lon, label):
    s = _series(tile_store, "dhw_severe_risk_days_per_year", lat, lon)
    if s is None:
        return None
    axis, values = s
    first = _window_mean(values, slice(0, 5))
    last = _window_mean(values, slice(-5, None))
    if first is None or last is None:
        return None
    answer = (
        f"Coral reefs near **{label}** now face severe bleaching risk on about "
        f"**{last:.0f} days per year** (average of the last five years), compared with "
        f"{first:.0f} days per year at the start of the record in {str(axis[0])[:4]}. "
        f"Severe risk means accumulated heat stress high enough to cause widespread "
        f"bleaching and coral mortality."
    )
    return answer, {"metric_id": "dhw_severe_risk_days_per_year"}


def _gen_local_rank(tile_store, lat, lon, label):
    ranking = tile_store.rankings.get(("t2m_yearly_mean_c", "mean"))
    if not ranking:
        return None
    # Nearest ranked city within ~0.35° (roughly one 0.25° grid cell).
    best_idx, best_dist = None, 0.35
    for i, city in enumerate(ranking):
        d = max(abs(city["lat"] - lat), abs(city["lon"] - lon))
        if d < best_dist:
            best_idx, best_dist = i, d
    if best_idx is None:
        return None
    entry = ranking[best_idx]
    total = len(ranking)
    rank = best_idx + 1
    hotter_than_pct = (total - rank) / total * 100
    answer = (
        f"**{label}** ranks **#{rank:,}** warmest out of {total:,} cities worldwide in our "
        f"data, with a mean annual temperature of **{_tok(entry['value'])}** — warmer than "
        f"{hotter_than_pct:.0f}% of ranked cities."
    )
    return answer, {"metric_id": "t2m_yearly_mean_c"}


_GENERATORS = {
    "local_temp_trend": _gen_local_temp_trend,
    "local_summer_heat": _gen_local_summer_heat,
    "local_night_cold": _gen_local_night_cold,
    "rainfall_local": _gen_rainfall_local,
    "local_winters": _gen_local_winters,
    "local_vs_global": _gen_local_vs_global,
    "sea_temp_local": _gen_sea_temp_local,
    "coral_risk_local": _gen_coral_risk_local,
    "local_rank": _gen_local_rank,
}


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------


def generate(
    question_id: str,
    lat: float,
    lon: float,
    label: str,
    tile_store: Any,
    temperature_unit: str = "C",
) -> dict | None:
    """
    Build a templated answer for a location question, or None to fall back to
    the LLM. Returns {"answer", "locations", "charts", "follow_up_ids"}.
    """
    node = QUESTION_TREE.get(question_id)
    generator = _GENERATORS.get(question_id)
    if node is None or generator is None or not node.requires_location:
        return None

    # Short display name: "Paris, Île-de-France, France" → "Paris"
    short_label = label.split(",")[0].strip() or label

    try:
        result = generator(tile_store, lat, lon, short_label)
    except Exception:
        return None
    if result is None:
        return None
    answer, chart_spec = result

    from .canned import build_canned_charts

    locations = [{"label": short_label, "lat": lat, "lon": lon}]
    extra_region_ids = (chart_spec or {}).pop("extra_region_ids", None)
    charts = (
        build_canned_charts(locations, chart_spec, tile_store, temperature_unit)
        if chart_spec
        else []
    )
    if extra_region_ids:
        from . import tools as _tools
        from .orchestrator import _build_chart_payloads

        series_results = []
        for region_id in extra_region_ids:
            r = _tools.get_region_metric_series(
                region_id=region_id,
                metric_id=chart_spec["metric_id"],
                aggregation="mean",
                tile_store=tile_store,
                temperature_unit=temperature_unit,
            )
            if "error" not in r and "data" in r:
                series_results.append(r)
        if series_results and charts:
            # Merge region series into the local chart (same metric).
            for extra in _build_chart_payloads(series_results, tile_store):
                if extra["series"]:
                    charts[0]["series"].extend(extra["series"])

    return {
        "answer": answer,
        "locations": locations,
        "charts": charts,
        "follow_up_ids": node.follow_up_ids,
    }
