"use client";

import { useMemo } from "react";
import type { MapLayerOption } from "@/components/MapLibreGlobe";
import { useReleaseResolution } from "@/hooks/explorer/useReleaseResolution";
import type { ReleaseLayer } from "@/hooks/explorer/useReleaseResolution";
import { type Bbox, mercatorAspect } from "@/lib/story/mercator";
import {
  textureInfo,
  toMapLayerOption,
  useClimateApiBase,
} from "@/lib/story/releaseAssets";
import AnomalyMap from "@/components/story/AnomalyMap";
import DownloadIcon from "@/components/story/DownloadIcon";
import {
  downloadAnomalyMap,
  downloadAnomalyMapPair,
} from "@/lib/story/anomalyMapRender";
import GlobeBoundary from "@/components/story/GlobeBoundary";
import ShareButton from "@/components/story/ShareButton";
import SwipeCompare from "@/components/story/SwipeCompare";
import StoryGlobe, {
  type GlobeStep,
  type GlobeStepGroup,
  type GlobeStepSlider,
} from "@/components/story/StoryGlobe";
import type {
  PanelChartSpec,
  PanelHighlight,
} from "@/components/story/LocationPanel";
import styles from "@/components/story/story.module.css";
import s from "./summerStory.module.css";
import {
  BASE_LABEL,
  DATA,
  STORY_COUNTRIES,
  days,
  hottestOnRecord,
  listOf,
  n0,
  n1,
  pct,
} from "./storyData";
import { TITLE as TITLE_VALUE } from "./meta";
import {
  CumulativeRain,
  HeatRainScatter,
  HeatTimeline,
  JointHistoryPicker,
  RainGrid,
  SpaghettiTabs,
  WarmingBars,
} from "./charts";

export { TITLE } from "./meta";

const EUROPE_LINES = "/story/europe-lines.json";
const WORLD_LINES = "/story/world-lines.json";
// Rainfall is a land story here, so the hemisphere map knocks the sea out.
const LAND_MASK = "/story/land-mask-mercator.png";
// The Copernicus licence prescribes this wording for modified products.
const ATTRIB =
  "Contains modified Copernicus Climate Change Service information 2026";
const RAIN_SCALE = ["#5c3708", "#c98a10", "#f7f7f7", "#74add1", "#313695"];
const HEAT_SCALE = [
  "#ffffcc",
  "#ffeda0",
  "#fed976",
  "#feb24c",
  "#fd8d3c",
  "#fc4e2a",
  "#e31a1c",
  "#b10026",
];
// Wide Europe frame: Iberia to the Baltic, the Maghreb coast to Scandinavia.
const EUROPE_BBOX: Bbox = { west: -13, south: 34, east: 42, north: 63 };
// The northern hemisphere's land, for the "was it everywhere?" rainfall map.
const WORLD_BBOX: Bbox = { west: -170, south: -10, east: 179, north: 72 };
const GLOBE_BBOX: [number, number, number, number] = [-12, 35, 32, 62];

// The opener pairs heat and rain, so both cover the same 76 days. The 11-14
// August window is still on the globe below, where the reader can step through
// the individual episodes.
const SEASON_HEAT_LAYER = "summer_2026_heat";
const RAIN_LAYER = "summer_2026_rainfall_deficit";
const LATE_RAIN_LAYER = "late_aug_2026_rain";

// The globe steps evenly across the summer rather than through the four
// hand-picked June/July episodes: those are the previous case study's subject,
// and unevenly spaced windows made the gaps look like quiet periods. Fifteen
// five-day windows, none straddling a month, generated by
// scripts/make_heat_window_registry.py.
const HEAT_WINDOWS: GlobeStep[] = [
  { id: "t2m_heatslider_sum26_00", label: "1–5 Jun" },
  { id: "t2m_heatslider_sum26_01", label: "6–10 Jun" },
  { id: "t2m_heatslider_sum26_02", label: "11–15 Jun" },
  { id: "t2m_heatslider_sum26_03", label: "16–20 Jun" },
  { id: "t2m_heatslider_sum26_04", label: "21–25 Jun" },
  { id: "t2m_heatslider_sum26_05", label: "26–30 Jun" },
  { id: "t2m_heatslider_sum26_06", label: "1–5 Jul" },
  { id: "t2m_heatslider_sum26_07", label: "6–10 Jul" },
  { id: "t2m_heatslider_sum26_08", label: "11–15 Jul" },
  { id: "t2m_heatslider_sum26_09", label: "16–20 Jul" },
  { id: "t2m_heatslider_sum26_10", label: "21–25 Jul" },
  { id: "t2m_heatslider_sum26_11", label: "26–31 Jul" },
  { id: "t2m_heatslider_sum26_12", label: "1–5 Aug" },
  { id: "t2m_heatslider_sum26_13", label: "6–10 Aug" },
  { id: "t2m_heatslider_sum26_14", label: "11–15 Aug" },
  { id: "t2m_heatslider_sum26_15", label: "16–20 Aug" },
  { id: "t2m_heatslider_sum26_16", label: "21–25 Aug" },
  { id: "t2m_heatslider_sum26_17", label: "26–31 Aug" },
];
// Two rain windows: the dry stretch the story is about, and the fortnight it
// broke. Without the second one the globe stopped at 15 August while the
// section promised the whole summer.
const RAIN_STEPS: GlobeStep[] = [
  { id: RAIN_LAYER, label: "1 Jun – 15 Aug" },
  { id: LATE_RAIN_LAYER, label: "16–31 Aug" },
];
const GLOBE_STEPS: GlobeStep[] = [...HEAT_WINDOWS, ...RAIN_STEPS];
const GLOBE_SLIDER: GlobeStepSlider = { label: "Heat", steps: HEAT_WINDOWS };
const GLOBE_GROUPS: GlobeStepGroup[] = [{ label: "Rain", steps: RAIN_STEPS }];

// Each map window as a date span, so the panel can mark it on the matching
// chart: heat windows on the temperature trace, rain windows on the rainfall.
const WINDOW_SPANS: [string, string, string][] = [
  ["t2m_heatslider_sum26_00", "2026-06-01", "2026-06-05"],
  ["t2m_heatslider_sum26_01", "2026-06-06", "2026-06-10"],
  ["t2m_heatslider_sum26_02", "2026-06-11", "2026-06-15"],
  ["t2m_heatslider_sum26_03", "2026-06-16", "2026-06-20"],
  ["t2m_heatslider_sum26_04", "2026-06-21", "2026-06-25"],
  ["t2m_heatslider_sum26_05", "2026-06-26", "2026-06-30"],
  ["t2m_heatslider_sum26_06", "2026-07-01", "2026-07-05"],
  ["t2m_heatslider_sum26_07", "2026-07-06", "2026-07-10"],
  ["t2m_heatslider_sum26_08", "2026-07-11", "2026-07-15"],
  ["t2m_heatslider_sum26_09", "2026-07-16", "2026-07-20"],
  ["t2m_heatslider_sum26_10", "2026-07-21", "2026-07-25"],
  ["t2m_heatslider_sum26_11", "2026-07-26", "2026-07-31"],
  ["t2m_heatslider_sum26_12", "2026-08-01", "2026-08-05"],
  ["t2m_heatslider_sum26_13", "2026-08-06", "2026-08-10"],
  ["t2m_heatslider_sum26_14", "2026-08-11", "2026-08-15"],
  ["t2m_heatslider_sum26_15", "2026-08-16", "2026-08-20"],
  ["t2m_heatslider_sum26_16", "2026-08-21", "2026-08-25"],
  ["t2m_heatslider_sum26_17", "2026-08-26", "2026-08-31"],
  ["summer_2026_rainfall_deficit", "2026-06-01", "2026-08-15"],
  ["late_aug_2026_rain", "2026-08-16", "2026-08-31"],
];
const SPAN_BY_LAYER = new Map(
  WINDOW_SPANS.map(([id, from, to]) => [id, { from, to }]),
);

function highlightFor(layerId: string): PanelHighlight | null {
  const span = SPAN_BY_LAYER.get(layerId);
  if (!span) return null;
  const isRain = layerId === RAIN_LAYER || layerId === LATE_RAIN_LAYER;
  return {
    seriesKey: isRain ? "tp_daily_total" : "t2m_daily_mean",
    from: span.from,
    to: span.to,
    tone: isRain ? "rain" : "heat",
  };
}

const PANEL_CHARTS: PanelChartSpec[] = [
  {
    seriesKey: "t2m_daily_mean",
    title: "Daily mean temperature",
    kind: "line",
    unit: "°",
  },
  {
    seriesKey: "tp_daily_total",
    title: "Daily rainfall",
    kind: "bar",
    unit: " mm",
    fromZero: true,
  },
];

// Spain, France and Italy are the countries the outcome column is really
// about; the other two rows are there to show what not setting a record looks
// like, so they stay unemphasised.
const RECORD_SETTERS = new Set(["Spain", "France", "Italy"]);

const OUTCOMES: [string, string][] = [
  ["Spain", "Largest fire in its recorded history"],
  ["France", "Most land burned in a year on record"],
  ["Italy", "Longest in heat episodes, but no fire record"],
  ["Portugal", "Driest of the eight, and no fire record"],
  ["Greece", "Wetter than normal, and no fire record"],
];

const WARM_EUROPE = DATA.warm.find(([n]) => n === "Europe")![1];
const WARM_GLOBE = DATA.warm.find(([n]) => n.startsWith("Globe"))![1];
const WARM_LAND = DATA.warm.find(([n]) => n === "Global land")![1];
const RATIO_GLOBE = (WARM_EUROPE / WARM_GLOBE).toFixed(1);
const RATIO_LAND = (WARM_EUROPE / WARM_LAND).toFixed(1);

function Ref({ n }: { n: number }) {
  return (
    <sup>
      <a href={`#source-${n}`} aria-label={`Source ${n}`}>
        [{n}]
      </a>
    </sup>
  );
}

export default function SummerStory() {
  const { apiBase, mapAssetBase } = useClimateApiBase();
  const envDefaultReleaseRaw = process.env.NEXT_PUBLIC_RELEASE;
  const { requestedRelease, sessionRelease, releaseLayers } =
    useReleaseResolution(apiBase, envDefaultReleaseRaw);
  const release = sessionRelease ?? requestedRelease;
  const encodedRelease = encodeURIComponent(release);

  const layersById = useMemo(() => {
    const map = new Map<string, ReleaseLayer>();
    for (const layer of releaseLayers) map.set(layer.id, layer);
    return map;
  }, [releaseLayers]);

  const heat = textureInfo(
    layersById.get(SEASON_HEAT_LAYER),
    mapAssetBase,
    encodedRelease,
  );
  const rain = textureInfo(layersById.get(RAIN_LAYER), mapAssetBase, encodedRelease);

  const globeLayerOptions = useMemo<MapLayerOption[]>(() => {
    const options: MapLayerOption[] = [{ id: "none", label: "None" }];
    for (const step of [...GLOBE_STEPS, { id: SEASON_HEAT_LAYER, label: "" }]) {
      const layer = layersById.get(step.id);
      if (layer)
        options.push(toMapLayerOption(layer, mapAssetBase, encodedRelease));
    }
    return options;
  }, [layersById, mapAssetBase, encodedRelease]);
  const globeReady = globeLayerOptions.length > 1;

  const europeAspect = mercatorAspect(EUROPE_BBOX);

  const downloadWorld = () => {
    if (!rain) return;
    void downloadAnomalyMap(
      {
        textureUrl: rain.url,
        textureWidth: rain.width,
        textureHeight: rain.height,
        latMax: rain.latMax,
        bbox: WORLD_BBOX,
        linesUrl: WORLD_LINES,
        maskUrl: LAND_MASK,
      },
      {
        title: "Rainfall across the northern hemisphere, summer 2026",
        subtitle:
          "1 June – 15 August 2026 as a percentage of the " +
          BASE_LABEL +
          " normal, over land",
        sourceText: ATTRIB,
        scale: { min: "0%", max: "200% of normal", colors: RAIN_SCALE },
      },
      "summer-2026-rainfall-northern-hemisphere.png",
    );
  };

  const downloadPair = () => {
    if (!heat || !rain) return;
    void downloadAnomalyMapPair(
      {
        textureUrl: heat.url,
        textureWidth: heat.width,
        textureHeight: heat.height,
        latMax: heat.latMax,
        bbox: EUROPE_BBOX,
        linesUrl: EUROPE_LINES,
        label: "Heat · 2 m air temperature vs the " + BASE_LABEL + " average",
        scale: { min: "0°C", max: "+5°C above normal", colors: HEAT_SCALE },
      },
      {
        textureUrl: rain.url,
        textureWidth: rain.width,
        textureHeight: rain.height,
        latMax: rain.latMax,
        bbox: EUROPE_BBOX,
        linesUrl: EUROPE_LINES,
        label: "Rain · total precipitation, % of the " + BASE_LABEL + " normal",
        scale: { min: "0%", max: "200% of normal", colors: RAIN_SCALE },
      },
      {
        title: "Europe's summer of 2026: heat and rainfall",
        subtitle:
          "ERA5 2 m air temperature (t2m) and total precipitation (tp), " +
          "1 June – 15 August 2026 against " +
          BASE_LABEL,
        sourceText: ATTRIB,
      },
      "summer-2026-heat-and-rain.png",
    );
  };
  const fr = DATA.ranks.France;
  const es = DATA.ranks.Spain;
  const pt = DATA.rain.Portugal;
  const uk = DATA.monthly.grid["United Kingdom"];
  const ukRank = DATA.ranks["United Kingdom"];
  const hottest = hottestOnRecord();
  const dec = DATA.europeDecades;
  const peaks = DATA.peaks;

  return (
    <article className={styles.story}>
      <header className={styles.hero}>
        <div className={styles.eyebrowRow}>
          <p className={styles.eyebrow}>climate.you · Case study</p>
          <span className={styles.eyebrowActions}>
            <ShareButton title={TITLE_VALUE} />
            {/* eslint-disable-next-line @next/next/no-html-link-for-pages */}
            <a className={styles.backLink} href="/">
              <span aria-hidden="true">←</span> Back to the globe
            </a>
          </span>
        </div>
        <h1>{TITLE_VALUE}</h1>
        <p className={styles.dek}>
          Much of the northern hemisphere was hot this summer. Almost all of it
          still got its normal rain. Western Europe did not, and went on to
          lose more land to fire than in any summer on record. A look into the
          Copernicus ERA5/ERA5T record.
        </p>
        <p className={styles.published}>
          Published <time dateTime="2026-09-25">25 September 2026</time>
        </p>
        <p className={styles.meta}>
          Contains modified Copernicus Climate Change Service information 2026
          · ERA5/ERA5T 2&#8202;m air temperature and total precipitation ·
          record through 31 August 2026 · processed with the{" "}
          <a href="https://github.com/climate-you/climate">
            open-source pipeline
          </a>{" "}
          powering <a href="https://climate.you">climate.you</a>
        </p>
      </header>

      {/* ── Opening: heat and rain on the same frame ─────────────────────── */}
      {heat && rain ? (
        <SwipeCompare
          aspect={europeAspect}
          leftLabel="Heat, 1 Jun – 15 Aug"
          rightLabel="Rain, 1 Jun – 15 Aug"
          ariaLabel="Reveal the rainfall map over the heat map"
          left={
            <AnomalyMap
              textureUrl={heat.url}
              textureWidth={heat.width}
              textureHeight={heat.height}
              latMax={heat.latMax}
              bbox={EUROPE_BBOX}
              linesUrl={EUROPE_LINES}
              renderHeight={900}
              alt="Temperature anomaly over Europe, 1 June to 15 August 2026"
            />
          }
          right={
            <AnomalyMap
              textureUrl={rain.url}
              textureWidth={rain.width}
              textureHeight={rain.height}
              latMax={rain.latMax}
              bbox={EUROPE_BBOX}
              linesUrl={EUROPE_LINES}
              renderHeight={900}
              alt="Rainfall from 1 June to 15 August 2026 as a percentage of normal, Europe"
            />
          }
        />
      ) : (
        <div className={styles.swipe} style={{ aspectRatio: `${europeAspect}` }} />
      )}
      <div className={s.swipeFoot}>
        <div className={s.mapPair}>
        <div>
          <p className={s.scaleLabel}>Heat</p>
          <div className={styles.scale}>
            <span>0°C</span>
            <span className={styles.grad} />
            <span>+5°C above normal</span>
          </div>
        </div>
        <div>
          <p className={s.scaleLabel}>Rain</p>
          <div className={styles.scale}>
            <span>0%</span>
            <span className={s.gradRain} />
            <span>200% of normal</span>
          </div>
        </div>
        </div>
        {heat && rain ? (
          <DownloadIcon
            label="Download both maps"
            onClick={downloadPair}
            className={s.figDl}
          />
        ) : null}
      </div>
      <p className={styles.cap}>
        Two views of the same 76 days. <b>Heat:</b> mean air temperature from
        1 June to 15 August against the {BASE_LABEL} average for those dates.{" "}
        <b>Rain:</b> rainfall over the same window as a percentage of the{" "}
        {BASE_LABEL} normal.
      </p>

      <div className={s.openingGrid}>
        <div className={s.prose}>
          <p>
            More than 1.2 million acres burned across Europe this summer.
            <Ref n={1} /> Spain lost the largest single fire in its recorded
            history, near Ávila.<Ref n={2} /> More land burned in France than in
            any year since national records began.<Ref n={2} /> Across the two
            countries, more than 300,000 people were told to leave their homes.
            <Ref n={1} />
          </p>
          <p>
            It was a hot summer, but not only here. Russia spent{" "}
            <strong>{days("Russia")}</strong> days in heat episodes, Canada{" "}
            <strong>{days("Canada")}</strong>, China{" "}
            <strong>{days("China")}</strong>, Japan{" "}
            <strong>{days("Japan")}</strong>. Heat alone was not unusual this
            year.
          </p>
          <p>
            What set western Europe apart was that{" "}
            <em>the rain did not come with it</em>.
          </p>
        </div>
        <div className={`${styles.statsCol} ${s.railCol}`}>
          <div className={styles.stats}>
            <div className={styles.stat}>
              <span className={styles.num}>{days("France")}</span>
              <span className={styles.lab}>
                days in heat episodes in France, May to August
              </span>
            </div>
            <div className={styles.stat}>
              <span className={styles.num}>13 Aug</span>
              <span className={styles.lab}>
                the day the August heat peaked in the UK, France and Spain
                together
              </span>
            </div>
            <div className={`${styles.stat} ${styles.statDry} ${styles.statText}`}>
              <span className={styles.num}>Hottest &amp; driest</span>
              <span className={styles.lab}>
                France&apos;s summer was both, out of the {fr.n} summers since
                1979
              </span>
            </div>
            <div className={`${styles.stat} ${styles.statDry}`}>
              <span className={styles.num}>{n0(pct("Portugal"))}%</span>
              <span className={styles.lab}>
                of normal rainfall in Portugal, 1 June – 15 August, the driest
                of the eight European countries measured here
              </span>
            </div>
            <div className={styles.stat}>
              <span className={styles.num}>{days("Italy")}</span>
              <span className={styles.lab}>
                days in heat episodes in Italy, May to August, the most of any
                country measured
              </span>
            </div>
            <div className={`${styles.stat} ${styles.statNeutral}`}>
              <span className={styles.num}>{RATIO_GLOBE}×</span>
              <span className={styles.lab}>
                Europe&apos;s warming rate against the globe since 1979
              </span>
            </div>
          </div>
          <p className={styles.statsHint} aria-hidden="true">
            swipe for more →
          </p>
        </div>

        {/* ── 02 ─ display:contents, so the heading and opening paragraphs
            become rows of the grid above and the rail keeps running beside
            them; the chart then breaks out across both columns. ─────────── */}
        <section className={s.contents}>
          <h2 className={s.railHeading}>Heat, nearly everywhere</h2>
        <div className={s.prose}>
          <p>
            Summer 2026 did not arrive as a single heatwave. It came in
            episodes of different lengths, in different places, and they
            overlapped. France was in one for sixteen days from 13 June; for
            the week of <strong>18 to 24 June</strong> it was joined by Spain,
            Italy, Germany and the Netherlands, all five in an episode at the
            same time. That June spell is the subject of{" "}
            {/* eslint-disable-next-line @next/next/no-html-link-for-pages */}
            <a href="/stories/june-2026-heatwave">our previous case study</a>,
            which follows the heat dome as it tracked north-east across the
            continent.
          </p>
          <p>
            The last of them, in mid-August, was the United Kingdom&apos;s
            sharpest. On <strong>13 August the Met Office recorded
            38.1&#8202;°C at Kew Gardens, the fifth-hottest day in the UK
            record</strong>, and the second day of 2026 to reach
            38&#8202;°C.<Ref n={3} />{" "}Only 2022, the hottest year the UK has
            had, has managed two such days. Three days in 2026 reached
            37&#8202;°C.
          </p>
          <p>
            In our own gridded figures it was the hottest day of the year for
            the UK, at {n1(peaks["United Kingdom"].aug13)}&#8202;°C averaged
            across the whole country by land area. France and Spain were in the
            same episode and close to their own August peaks,{" "}
            {n1(peaks.France.aug13)}&#8202;°C and {n1(peaks.Spain.aug13)}
            &#8202;°C, though neither beat its June and July highs.
          </p>
        </div>
          <div className={s.fullWidth}>
            <HeatTimeline />
            <p className={s.defn}>
              This chart uses <b>daily maximum</b>{" "}temperature. Every
              national weather service defines a heatwave differently. The Met
              Office uses fixed county thresholds; Météo-France requires a
              daytime maximum <em>and</em> a night-time minimum to be passed
              together for three days and nights, on thresholds set per
              département.<Ref n={4} />{" "}The episodes here are not any one
              country&apos;s official heatwaves, and are not comparable to
              their published counts.
            </p>
          </div>
        </section>
      </div>

      {/* ── 03 ───────────────────────────────────────────────────────────── */}
      <section className={s.section}>
        <h2>The rain that never came</h2>
        <div className={s.prose}>
          <p>
            Heat on its own is survivable. What turns a hot summer into a
            burning one is what the heat arrives on: soil that has already
            given up its moisture, rivers running low, vegetation that has been
            drying since spring. So the second question is how much rain fell
            while all this was happening.
          </p>
          <p>
            In western Europe, not much. From 1 June to 15 August,{" "}
            <em>Portugal, Spain and France each received about half the rain
            they would normally expect</em>, and Germany was not far behind.
            Italy and the United Kingdom finished the window nearer normal,
            though that total hides a savage July in Britain.
          </p>
          <p>
            But the rain did not stop everywhere at once. In Iberia it was
            already failing in June. In Britain, June was{" "}
            <span className={s.wet}>wetter</span> than normal, at {n0(uk[0])}%,
            and the drought only began in July, when barely a third of the
            usual rain arrived.
          </p>
        </div>
        <RainGrid />
        <figure className={s.fig} style={{ marginTop: 26 }}>
          <div className={s.figHead}>
            <div>
              <h3 className={s.figTitle}>
                The same measure across the northern hemisphere
              </h3>
              <p className={s.figSub}>
                Rainfall 1 June – 15 August 2026 as a percentage of the{" "}
                {BASE_LABEL} normal, over land
              </p>
            </div>
            {rain ? (
              <DownloadIcon
                label="Download this map"
                onClick={downloadWorld}
                className={s.figDl}
              />
            ) : null}
          </div>
          <div className={s.worldMap}>
            {rain ? (
              <AnomalyMap
                textureUrl={rain.url}
                textureWidth={rain.width}
                textureHeight={rain.height}
                latMax={rain.latMax}
                bbox={WORLD_BBOX}
                linesUrl={WORLD_LINES}
                maskUrl={LAND_MASK}
                alt="Rainfall from 1 June to 15 August 2026 as a percentage of normal over land, northern hemisphere"
              />
            ) : (
              <div style={{ aspectRatio: `${mercatorAspect(WORLD_BBOX)}` }} />
            )}
          </div>
          <div className={styles.scale} style={{ marginTop: 10 }}>
            <span>0%</span>
            <span className={s.gradRain} />
            <span>200% of normal</span>
          </div>
          <figcaption className={s.figcap}>
            Land only, across the northern hemisphere, where it was summer.
            Rain over the ocean is not part of this story and is much noisier
            than rain over land, so the sea is left out. Nationally the big
            countries came out close to normal: the United States{" "}
            {n0(pct("United States"))}%, China {n0(pct("China"))}%, Canada{" "}
            {n0(pct("Canada"))}%, Russia {n0(pct("Russia"))}%. Two other brown
            patches are worth naming. <b>Southern Pakistan</b>{" "}is a real and
            severe failure of the monsoon, worse in places than anything in
            Europe: around Sukkur the window brought 1&#8202;mm against a
            normal of 68. <b>California</b>{" "}is the opposite case, an artefact
            of the ratio: its summers are normally almost rainless, so 1&#8202;mm
            against a normal of 7 reads as a deep deficit on a map while
            meaning very little on the ground. The grey gaps, most of the
            Sahara and the Arabian peninsula, are drier still and are left out
            entirely.
          </figcaption>
        </figure>
      </section>

      {/* ── 04 ───────────────────────────────────────────────────────────── */}
      <section className={s.section}>
        <h2>Heat on dry ground</h2>
        <div className={s.prose}>
          <p>
            The two halves of the story have been told separately so far: how
            hot each country was, then how dry. Neither on its own picks
            western Europe out. Plenty of the northern hemisphere was as hot; a
            handful of places were as dry. What follows puts both measurements
            on the same chart, one country per dot, to show which of them had
            to take the two together.
          </p>
        </div>
        <HeatRainScatter />
        <div className={s.prose}>
          <p>
            The dry corner is not an abstraction. The countries that landed in
            it are the ones where the summer ended in evacuations and burnt
            ground, and the ones just outside it came through without a
            national record to show for the heat.
          </p>
        </div>
        <div className={s.tableWrap}>
          <table className={s.table}>
            <thead>
              <tr>
                <th>Country</th>
                <th>Rainfall</th>
                <th>Heat days*</th>
                <th>Outcome</th>
              </tr>
            </thead>
            <tbody>
              {OUTCOMES.map(([n, outcome]) => {
                const r = pct(n);
                const d = DATA.daysInDryWindow[n] ?? 0;
                const hi = true;
                const record = RECORD_SETTERS.has(n);
                return (
                  <tr key={n} className={hi ? "hi" : ""}>
                    <td>{n}</td>
                    <td className={r < 60 ? "dry" : r < 100 ? "" : "cool"}>
                      {n0(r)}%
                    </td>
                    <td className={d > 40 ? "hot" : ""}>{d}</td>
                    <td className={`outcome${record ? " record" : ""}`}>
                      {outcome}
                    </td>
                  </tr>
                );
              })}
            </tbody>
          </table>
          <p className={s.tableNote}>
            * Days in heat episodes between 1 June and 15 August, the same
            window as the rainfall column.
          </p>
        </div>
        <div className={s.prose}>
          <p>
            Over those same eleven weeks Russia spent{" "}
            <strong>{DATA.daysInDryWindow.Russia}</strong> days in heat
            episodes, almost as many as France, and still finished on{" "}
            {n0(pct("Russia"))}% of its normal rain. Canada, China and Japan
            were all hot and all wet. Italy was in heat episodes longest of
            all, <strong>{DATA.daysInDryWindow.Italy}</strong> days, but at{" "}
            {n0(pct("Italy"))}% it was wetter than Spain or France, and it did
            not set the records they did.
          </p>
          <p>
            <strong>
              Heat was common this summer. Heat arriving on ground that had not
              been rained on was not.
            </strong>
          </p>
        </div>
      </section>

      {/* ── 05 ───────────────────────────────────────────────────────────── */}
      <section className={s.section}>
        <h2>The break, mid-August</h2>
        <div className={s.prose}>
          <p>
            Around the 16th of August the weather pattern broke and the
            Atlantic rain belt, which had been steered around western Europe
            for most of the summer, moved back over it. In the fortnight that
            followed,
            Portugal received{" "}
            <span className={s.wet}>
              {n0(pt.wet.obs)}&#8202;mm, {n0(pt.wet.pct)}% of normal for those
              two weeks, and {n1(pt.ratio)} times everything it had received in
              the preceding {n0(pt.dry.days)} days
            </span>
            .
          </p>
          <p>
            Elsewhere the return was real but ordinary: Spain{" "}
            {n0(pct("Spain", "wet"))}% of normal for the fortnight, Italy{" "}
            {n0(pct("Italy", "wet"))}%, Germany {n0(pct("Germany", "wet"))}%,
            France {n0(pct("France", "wet"))}%, the United Kingdom{" "}
            {n0(pct("United Kingdom", "wet"))}%. Not a deluge: just a normal
            fortnight, arriving after the fires were out.
          </p>
        </div>
        <CumulativeRain />
      </section>

      {/* ── 06 ───────────────────────────────────────────────────────────── */}
      <section className={s.section}>
        <h2>Your summer</h2>
        <div className={s.prose}>
          <p>
            Every number so far is a national average. Click your own location
            for the temperature and the rainfall where you live, day by day,
            from June to the end of August.
          </p>
        </div>
        {globeReady ? (
          <GlobeBoundary>
            <StoryGlobe
              layerOptions={globeLayerOptions}
              steps={GLOBE_STEPS}
              stepSlider={GLOBE_SLIDER}
              stepGroups={GLOBE_GROUPS}
              initialLayerId={HEAT_WINDOWS[4].id}
              flyToBbox={GLOBE_BBOX}
              apiBase={apiBase}
              release={release}
              panelFromDate="2026-06-01"
              panelToDate={DATA.dataThrough}
              panelPeriodLabel="summer 2026"
              panelCharts={PANEL_CHARTS}
              panelHighlightFor={highlightFor}
              autoAdvanceMs={0}
              downloadLabel="Download the map for this layer"
            />
          </GlobeBoundary>
        ) : (
          <div className={styles.globeStage}>
            <div className={styles.globeCanvasWrap} />
          </div>
        )}
        <p className={styles.cap}>
          Drag the slider to step through the whole summer in five-day
          windows, 1 June to 31 August.
          Each is measured against that month&apos;s own average, which is why
          Spain looks most extreme in late June rather than in July: its
          hottest <em>absolute</em>{" "}day came on 6 July, but July is normally
          hot in Spain, so the same heat is a smaller departure from normal.
          Click anywhere for that place&apos;s daily record. Values are for the
          0.25° grid cell around the point, not a weather station. The two
          rain windows are the dry stretch and the fortnight it broke. The
          window you pick is marked on the matching chart when you click a
          place.
        </p>
      </section>

      {/* ── 07 ───────────────────────────────────────────────────────────── */}
      <section className={s.section}>
        <h2>Has this happened before?</h2>
        <div className={s.prose}>
          <p>
            A hot, dry summer is not in itself remarkable; western Europe has
            had plenty. The question is whether this particular combination, at
            this size, has a precedent in the record. The chart below plots
            one dot per June–August since 1979, temperature against rainfall,
            with 2026 highlighted. If earlier summers were routinely hotter and
            drier, they would sit above and to the left of it.
          </p>
          <p>
            The heat, on its own, is not what separates these countries.
            In{" "}
            <strong>
              {hottest.length} of the {STORY_COUNTRIES.length}
            </strong>{" "}
            ({listOf(hottest)}) no summer since 1979 has been hotter than 2026.
            What varies is the rain. Switch country and watch the dot move
            sideways.
          </p>
        </div>
        <JointHistoryPicker />
        <div className={s.prose} style={{ marginTop: 26 }}>
          <p>
            For {listOf(hottest)} the corner is empty: nothing in the record
            was both hotter and drier. What separates them is how close the
            rest of the record comes. <strong>France</strong> stands alone in
            having no summer that beat it on <em>either</em> measure, hotter or
            drier. Spain has two drier, Italy five, the Netherlands seven, the
            United Kingdom ten.
          </p>
          <p>
            The United Kingdom is the case that shows heat is not the whole
            story. It had its hottest summer in {ukRank.n} years and it did
            burn: EFFIS counted about{" "}
            <strong>23,400 hectares</strong> across 72 fires larger than 30
            hectares by 10 August.<Ref n={5} />{" "}But that is roughly half the
            area lost in 2025, which remains the UK&apos;s worst year in the
            EFFIS record at 47,900 hectares. Ten of its {ukRank.n} summers were
            drier than 2026. Heat without the same depth of drought produced a
            bad fire year, not a record one.
          </p>
          <p>
            Two break the pattern on the dry axis.{" "}
            <span className={s.wet}>Portugal</span> finished its summer{" "}
            <em>wetter</em> than normal ({n0(DATA.ranks.Portugal.pct)}%) once
            the late-August rain is counted, and Greece was both cooler and
            wetter than most of the record. Neither was among the countries
            named in the season&apos;s fire reporting, which centred on Spain,
            France and Italy.<Ref n={1} />
          </p>
          <p>
            It is not that heat is new, or that dry summers are new. It is that
            across western Europe they have not arrived together at this size
            before: not in France, not in Spain, and not in a United Kingdom
            that has just had its hottest summer of the {ukRank.n} on record.
          </p>
        </div>
        <SpaghettiTabs />
      </section>

      {/* ── 08 ───────────────────────────────────────────────────────────── */}
      <section className={s.section}>
        <h2>The long view</h2>
        <div className={s.prose}>
          <p>
            None of this happened to a stable climate. Europe has warmed by{" "}
            <strong>{WARM_EUROPE.toFixed(2)}&#8202;°C per decade since 1979</strong>.
            Against the whole planet, land and ocean together, that is{" "}
            <strong>{RATIO_GLOBE} times the global rate</strong>; against the
            world&apos;s land alone, which warms faster than the sea,{" "}
            <strong>{RATIO_LAND} times</strong>.
          </p>
          <p>
            Europe&apos;s last five years averaged{" "}
            <strong>{n1(dec.siteDelta)}&#8202;°C</strong> warmer than its{" "}
            {dec.siteBase[0]}–{dec.siteBase[1]} average.
          </p>
        </div>
        <WarmingBars />
        <div className={s.prose} style={{ marginTop: 26 }}>
          <p>
            Warming does not decide what any one summer does, but it sets the
            ground the weather arrives on. That is the summer this page has
            measured. Heat almost everywhere in the northern hemisphere, and
            rain nearly everywhere it was expected, except across a band of
            western Europe where the two failed to arrive together. Whether
            2026 reads as an outlier or as an early draft of an ordinary summer
            is not something the record can answer yet. It can only say that
            nothing in the last {fr.n} years looks quite like it.
          </p>
        </div>
      </section>

      {/* ── Methods, sources ─────────────────────────────────────────────── */}
      <footer className={styles.methods}>
        <h2 className={s.footHead}>How to read these numbers</h2>
        <p>
          2&#8202;m air temperature
          and total precipitation from the Copernicus ERA5 climate record at
          0.25° resolution. ERA5 is the ECMWF reanalysis, a physically
          consistent reconstruction of past weather; the most recent months use
          its preliminary near-real-time release, ERA5T, which is revised later.
          The data is ingested and tiled by the{" "}
          <a href="https://github.com/climate-you/climate">
            open-source pipeline
          </a>{" "}
          that powers <a href="https://climate.you">climate.you</a>, the same
          dataset behind the interactive globe. Data runs through 31 August
          2026.
        </p>
        <ul className={s.methodsList}>
          <li>
            <b>Grid values are not station values.</b>{" "}A 0.25° cell is about
            19 × 28&#8202;km and averages town with countryside, so it runs
            cooler than the hottest thermometer inside it. Station records
            quoted here come from the national weather service, not from us.
          </li>
          <li>
            <b>Heat episodes are ours, not any country&apos;s official
            heatwaves.</b>{" "}Three or more consecutive days above that
            country&apos;s own {BASE_LABEL} day-of-year 90th percentile of daily
            maximum, ±7-day window, on the area-weighted national average.
            National definitions differ and none travels across borders.
          </li>
          <li>
            <b>Rainfall as a percentage of normal</b> is total observed divided
            by total expected over the window, where the expected total comes
            from the {BASE_LABEL} monthly climatology.
          </li>
          <li>
            <b>Two windows are in play</b>: 1 June – 15 August for the rainfall
            deficit, and the full June–August for the historical comparison.
            Each is named wherever it is used.
          </li>
          <li>
            <b>We show a coincidence, not a cause.</b> For the attribution see
            World Weather Attribution on compounding wildfire drivers in France
            and Spain.<Ref n={6} />
          </li>
        </ul>
        <div className={s.sources}>
          <h2 className={s.footHead}>Sources</h2>
          <ol>
            <li id="source-1">
              CNN, 10 August 2026,{" "}
              <a href="https://www.cnn.com/2026/08/10/climate/europe-heatwave-wildfire-intl-hnk">
                Europe&apos;s heatwave and wildfires
              </a>
              : area burned and evacuations.
            </li>
            <li id="source-2">
              World Economic Forum,{" "}
              <a href="https://www.weforum.org/stories/nature-and-biodiversity/europe-heatwaves-wildfires-charts/">
                Europe&apos;s heatwaves and wildfires, in charts
              </a>
              : the Ávila fire and France&apos;s annual record.
            </li>
            <li id="source-3">
              Met Office, 13 August 2026,{" "}
              <a
                href="https://www.metoffice.gov.uk/about-us/news-and-media/media-centre/weather-and-climate-news/2026/latest-heatwave-peaks-with-381c-recorded-and-rain-on-the-horizon-in-the-south"
                target="_blank"
                rel="noreferrer"
              >
                Latest heatwave peaks with 38.1°C recorded
              </a>
              : the Kew Gardens reading, its place in the UK record, and the
              count of 38&#8202;°C and 37&#8202;°C days in 2026.
            </li>
            <li id="source-4">
              Météo-France,{" "}
              <a
                href="https://meteofrance.com/actualites-et-dossiers/comprendre-la-meteo/canicule-vague-ou-pic-de-chaleur"
                target="_blank"
                rel="noreferrer"
              >
                Canicule, vague ou pic de chaleur : quelles différences ?
              </a>
              : the paired day and night thresholds.
            </li>
            <li id="source-5">
              European Forest Fire Information System (EFFIS) annual statistics
              for the United Kingdom, as summarised in{" "}
              <a
                href="https://en.wikipedia.org/wiki/2026_United_Kingdom_wildfires"
                target="_blank"
                rel="noreferrer"
              >
                2026 United Kingdom wildfires
              </a>
              : area burned in 2026 and the 2025 comparison.
            </li>
            <li id="source-6">
              World Weather Attribution,{" "}
              <a
                href="https://www.worldweatherattribution.org/climate-change-increases-likelihood-of-compounding-drivers-of-severe-wildfire-conditions-in-france-and-spain/"
                target="_blank"
                rel="noreferrer"
              >
                Climate change increases likelihood of compounding drivers of
                severe wildfire conditions in France and Spain
              </a>
              .
            </li>
          </ol>
        </div>
        <div className={s.rights}>
          <h2 className={s.footHead}>Attribution and rights</h2>
          <p>
            Generated using Copernicus Climate Change Service information 2026.
            Neither the European Commission nor ECMWF is responsible for any
            use that may be made of the Copernicus information or data this
            page contains.
          </p>
          <p>
            © 2026 Benoit Leveau &amp; Fanny Chaléon. This article, its
            figures, and images exported from it are all rights reserved and
            are not covered by the pipeline&apos;s AGPL licence.{" "}
            <a
              href="https://github.com/climate-you/climate/blob/main/CONTENT-LICENSE.md"
              target="_blank"
              rel="noreferrer"
            >
              Terms
            </a>
            .
          </p>
        </div>
      </footer>
    </article>
  );
}
