from __future__ import annotations

# Maps canonical continent names (lower-cased) to ISO 3166-1 alpha-2 country codes.
CONTINENT_TO_CC: dict[str, frozenset[str]] = {
    "africa": frozenset(
        {
            "AO",
            "BF",
            "BI",
            "BJ",
            "BW",
            "CD",
            "CF",
            "CG",
            "CI",
            "CM",
            "CV",
            "DJ",
            "DZ",
            "EG",
            "EH",
            "ER",
            "ET",
            "GA",
            "GH",
            "GM",
            "GN",
            "GQ",
            "GW",
            "KE",
            "KM",
            "LR",
            "LS",
            "LY",
            "MA",
            "MG",
            "ML",
            "MR",
            "MU",
            "MW",
            "MZ",
            "NA",
            "NE",
            "NG",
            "RE",
            "RW",
            "SC",
            "SD",
            "SH",
            "SL",
            "SN",
            "SO",
            "SS",
            "ST",
            "SZ",
            "TD",
            "TG",
            "TN",
            "TZ",
            "UG",
            "YT",
            "ZA",
            "ZM",
            "ZW",
        }
    ),
    "antarctica": frozenset({"AQ", "BV", "GS", "HM", "TF"}),
    "asia": frozenset(
        {
            "AE",
            "AF",
            "AM",
            "AZ",
            "BD",
            "BH",
            "BN",
            "BT",
            "CC",
            "CN",
            "CX",
            "CY",
            "GE",
            "HK",
            "ID",
            "IL",
            "IN",
            "IO",
            "IQ",
            "IR",
            "JO",
            "JP",
            "KG",
            "KH",
            "KP",
            "KR",
            "KW",
            "KZ",
            "LA",
            "LB",
            "LK",
            "MM",
            "MN",
            "MO",
            "MV",
            "MY",
            "NP",
            "OM",
            "PH",
            "PK",
            "PS",
            "QA",
            "SA",
            "SG",
            "SY",
            "TH",
            "TJ",
            "TL",
            "TM",
            "TR",
            "TW",
            "UZ",
            "VN",
            "YE",
        }
    ),
    "europe": frozenset(
        {
            "AD",
            "AL",
            "AT",
            "BA",
            "BE",
            "BG",
            "BY",
            "CH",
            "CZ",
            "DE",
            "DK",
            "EE",
            "ES",
            "FI",
            "FO",
            "FR",
            "GB",
            "GG",
            "GI",
            "GR",
            "HR",
            "HU",
            "IE",
            "IM",
            "IS",
            "IT",
            "JE",
            "LI",
            "LT",
            "LU",
            "LV",
            "MC",
            "MD",
            "ME",
            "MK",
            "MT",
            "NL",
            "NO",
            "PL",
            "PT",
            "RO",
            "RS",
            "RU",
            "SE",
            "SI",
            "SJ",
            "SK",
            "SM",
            "UA",
            "VA",
            "XK",
        }
    ),
    "north america": frozenset(
        {
            "AG",
            "AI",
            "AW",
            "BB",
            "BL",
            "BM",
            "BS",
            "BZ",
            "CA",
            "CR",
            "CU",
            "DM",
            "DO",
            "GD",
            "GL",
            "GP",
            "GT",
            "HN",
            "HT",
            "JM",
            "KN",
            "KY",
            "LC",
            "MF",
            "MQ",
            "MS",
            "MX",
            "NI",
            "PA",
            "PM",
            "PR",
            "SV",
            "TC",
            "TT",
            "US",
            "VC",
            "VG",
            "VI",
        }
    ),
    "oceania": frozenset(
        {
            "AS",
            "AU",
            "CK",
            "FJ",
            "FM",
            "GU",
            "KI",
            "MH",
            "MP",
            "NC",
            "NF",
            "NR",
            "NU",
            "NZ",
            "PF",
            "PG",
            "PW",
            "SB",
            "TK",
            "TO",
            "TV",
            "UM",
            "VU",
            "WF",
            "WS",
        }
    ),
    "south america": frozenset(
        {
            "AR",
            "BO",
            "BR",
            "CL",
            "CO",
            "EC",
            "FK",
            "GF",
            "GY",
            "PE",
            "PY",
            "SR",
            "UY",
            "VE",
        }
    ),
}

# Common aliases → canonical key in CONTINENT_TO_CC
CONTINENT_ALIASES: dict[str, str] = {
    "southern america": "south america",
    "latin america": "south america",
    "central america": "north america",
    "caribbean": "north america",
    "middle east": "asia",
    "australasia": "oceania",
    "australia": "oceania",
    "pacific": "oceania",
}


# Approximate bounding boxes [west, south, east, north] for continents.
# Used by the chat frontend to fly to a continent when it answers a regional question.
CONTINENT_BBOXES: dict[str, tuple[float, float, float, float]] = {
    "africa": (-20.0, -35.0, 52.0, 38.0),
    "antarctica": (-180.0, -90.0, 180.0, -60.0),
    "asia": (25.0, -10.0, 180.0, 82.0),
    "europe": (-25.0, 34.0, 45.0, 72.0),
    "north america": (-168.0, 5.0, -52.0, 84.0),
    "oceania": (110.0, -50.0, 180.0, 10.0),
    "south america": (-82.0, -57.0, -33.0, 15.0),
}


def resolve_continent(name: str) -> frozenset[str] | None:
    """Return the set of country codes for the given continent name, or None if unknown."""
    key = name.strip().casefold()
    key = CONTINENT_ALIASES.get(key, key)
    return CONTINENT_TO_CC.get(key)
